/** @type {import('tailwindcss').Config} */

module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'hv-primary': {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        'hv-secondary': {
          50: '#fdf4ff',
          100: '#fae8ff',
          200: '#f5d0fe',
          300: '#f0abfc',
          400: '#e879f9',
          500: '#d946ef',
          600: '#c026d3',
          700: '#a21caf',
          800: '#86198f',
          900: '#701a75',
        },
        'hv-accent': {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
        'hv-ui': {
          'background': '#1a1a1a',
          'surface': '#2d2d2d',
          'border': '#404040',
          'text': '#ffffff',
          'text-secondary': '#a3a3a3',
        },
        'hv-status': {
          'success': '#22c55e',
          'warning': '#f59e0b',
          'error': '#ef4444',
          'info': '#3b82f6',
        },
        'hv-rarity': {
          'common': '#94a3b8',
          'uncommon': '#22c55e',
          'rare': '#3b82f6',
          'epic': '#8b5cf6',
          'legendary': '#f59e0b',
          'mythic': '#ef4444',
        },
        'hv-theme': {
          'light': {
            'background': '#ffffff',
            'surface': '#f3f4f6',
            'text': '#1f2937',
            'border': '#e5e7eb',
          },
          'dark': {
            'background': '#1a1a1a',
            'surface': '#2d2d2d',
            'text': '#ffffff',
            'border': '#404040',
          },
        },
      },
      spacing: {
        '128': '32rem',
        '144': '36rem',
        '160': '40rem',
        '192': '48rem',
        '256': '64rem',
      },
      borderRadius: {
        'hv': '0.5rem',
        'hv-lg': '1rem',
        'hv-xl': '1.5rem',
        'hv-2xl': '2rem',
        'hv-3xl': '3rem',
        'hv-full': '9999px',
      },
      animation: {
        'hv-spin': 'spin 1s linear infinite',
        'hv-pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'hv-bounce': 'bounce 1s infinite',
        'hv-float': 'float 3s ease-in-out infinite',
        'hv-shake': 'shake 0.5s cubic-bezier(.36,.07,.19,.97) both',
        'hv-fade-in': 'fadeIn 0.5s ease-in-out',
        'hv-fade-out': 'fadeOut 0.5s ease-in-out',
        'hv-slide-in': 'slideIn 0.5s ease-in-out',
        'hv-slide-out': 'slideOut 0.5s ease-in-out',
        'hv-zoom-in': 'zoomIn 0.5s ease-in-out',
        'hv-zoom-out': 'zoomOut 0.5s ease-in-out',
        'hv-rotate': 'rotate 1s linear infinite',
        'hv-ping': 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        shake: {
          '10%, 90%': { transform: 'translate3d(-1px, 0, 0)' },
          '20%, 80%': { transform: 'translate3d(2px, 0, 0)' },
          '30%, 50%, 70%': { transform: 'translate3d(-4px, 0, 0)' },
          '40%, 60%': { transform: 'translate3d(4px, 0, 0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideIn: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideOut: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        zoomIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        zoomOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
        rotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        ping: {
          '75%, 100%': { transform: 'scale(2)', opacity: '0' },
        },
      },
      fontFamily: {
        'hv': ['Inter', 'system-ui', 'sans-serif'],
        'hv-display': ['Poppins', 'system-ui', 'sans-serif'],
        'hv-mono': ['JetBrains Mono', 'monospace'],
        'hv-fancy': ['Playfair Display', 'serif'],
        'hv-pixel': ['Press Start 2P', 'cursive'],
      },
      fontSize: {
        'hv-xs': ['0.75rem', { lineHeight: '1rem' }],
        'hv-sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'hv-base': ['1rem', { lineHeight: '1.5rem' }],
        'hv-lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'hv-xl': ['1.25rem', { lineHeight: '1.75rem' }],
        'hv-2xl': ['1.5rem', { lineHeight: '2rem' }],
        'hv-3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        'hv-4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        'hv-5xl': ['3rem', { lineHeight: '1' }],
        'hv-6xl': ['3.75rem', { lineHeight: '1' }],
        'hv-7xl': ['4.5rem', { lineHeight: '1' }],
        'hv-8xl': ['6rem', { lineHeight: '1' }],
        'hv-9xl': ['8rem', { lineHeight: '1' }],
      },
      boxShadow: {
        'hv': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'hv-md': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'hv-lg': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'hv-xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        'hv-inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        'hv-glow': '0 0 15px rgba(59, 130, 246, 0.5)',
        'hv-glow-lg': '0 0 30px rgba(59, 130, 246, 0.5)',
        'hv-glow-xl': '0 0 45px rgba(59, 130, 246, 0.5)',
        'hv-neon': '0 0 5px theme(colors.hv-primary.500), 0 0 20px theme(colors.hv-primary.500)',
      },
      backdropBlur: {
        'hv': '8px',
        'hv-md': '12px',
        'hv-lg': '16px',
        'hv-xl': '24px',
        'hv-2xl': '40px',
        'hv-3xl': '64px',
      },
      backgroundImage: {
        'hv-gradient': 'linear-gradient(to right, var(--tw-gradient-stops))',
        'hv-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'hv-conic': 'conic-gradient(var(--tw-gradient-stops))',
        'hv-diagonal': 'linear-gradient(45deg, var(--tw-gradient-stops))',
        'hv-radial-glow': 'radial-gradient(circle at center, var(--tw-gradient-stops))',
      },
      transitionProperty: {
        'hv': 'all',
        'hv-transform': 'transform',
        'hv-opacity': 'opacity',
        'hv-colors': 'background-color, border-color, color, fill, stroke',
        'hv-shadow': 'box-shadow',
        'hv-filter': 'filter',
        'hv-backdrop': 'backdrop-filter',
      },
      transitionDuration: {
        'hv': '150ms',
        'hv-fast': '100ms',
        'hv-slow': '300ms',
        'hv-slower': '500ms',
        'hv-slowest': '1000ms',
      },
      transitionTimingFunction: {
        'hv': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'hv-in': 'cubic-bezier(0.4, 0, 1, 1)',
        'hv-out': 'cubic-bezier(0, 0, 0.2, 1)',
        'hv-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'hv-bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },
      zIndex: {
        'hv-negative': '-1',
        'hv-0': '0',
        'hv-10': '10',
        'hv-20': '20',
        'hv-30': '30',
        'hv-40': '40',
        'hv-50': '50',
        'hv-auto': 'auto',
        'hv-modal': '1000',
        'hv-overlay': '2000',
        'hv-tooltip': '3000',
      },
      screens: {
        'hv-sm': '640px',
        'hv-md': '768px',
        'hv-lg': '1024px',
        'hv-xl': '1280px',
        'hv-2xl': '1536px',
        'hv-3xl': '1920px',
        'hv-4xl': '2560px',
      },
      container: {
        center: true,
        padding: {
          DEFAULT: '1rem',
          'hv-sm': '2rem',
          'hv-lg': '4rem',
          'hv-xl': '5rem',
          'hv-2xl': '6rem',
        },
      },
      gridTemplateColumns: {
        'hv-auto': 'repeat(auto-fit, minmax(250px, 1fr))',
        'hv-fixed': 'repeat(3, minmax(0, 1fr))',
        'hv-responsive': 'repeat(auto-fit, minmax(300px, 1fr))',
      },
      gridTemplateRows: {
        'hv-auto': 'repeat(auto-fit, minmax(200px, 1fr))',
        'hv-fixed': 'repeat(3, minmax(0, 1fr))',
        'hv-responsive': 'repeat(auto-fit, minmax(250px, 1fr))',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/line-clamp'),
    function({ addUtilities }) {
      const newUtilities = {
        '.hv-scrollbar': {
          '&::-webkit-scrollbar': {
            width: '8px',
            height: '8px',
          },
          '&::-webkit-scrollbar-track': {
            background: '#2d2d2d',
            borderRadius: '4px',
          },
          '&::-webkit-scrollbar-thumb': {
            background: '#4d4d4d',
            borderRadius: '4px',
            '&:hover': {
              background: '#5d5d5d',
            },
          },
        },
        '.hv-text-shadow': {
          'text-shadow': '0 2px 4px rgba(0,0,0,0.1)',
        },
        '.hv-text-shadow-lg': {
          'text-shadow': '0 4px 8px rgba(0,0,0,0.12)',
        },
        '.hv-text-shadow-none': {
          'text-shadow': 'none',
        },
        '.hv-blur-backdrop': {
          'backdrop-filter': 'blur(8px)',
        },
        '.hv-glass': {
          'background': 'rgba(255, 255, 255, 0.1)',
          'backdrop-filter': 'blur(10px)',
          'border': '1px solid rgba(255, 255, 255, 0.2)',
        },
        '.hv-glass-dark': {
          'background': 'rgba(0, 0, 0, 0.1)',
          'backdrop-filter': 'blur(10px)',
          'border': '1px solid rgba(255, 255, 255, 0.1)',
        },
      }
      addUtilities(newUtilities)
    },
  ],
}